package github

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// PROptions holds the data needed to open a GitHub pull request.
type PROptions struct {
	Slug     string
	Branch   string
	Task     string
	LogPath  string
	RepoRoot string
}

// PushBranch pushes a branch to the origin remote and sets its upstream.
func PushBranch(repoRoot, branch string) error {
	cmd := exec.Command("git", "push", "-u", "origin", branch)
	cmd.Dir = repoRoot
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git push failed for branch %q: %w\n%s", branch, err, string(out))
	}
	return nil
}

// CreatePR opens a GitHub pull request via the gh CLI and returns the PR URL.
func CreatePR(opts PROptions) (string, error) {
	body := buildPRBody(opts)

	cmd := exec.Command("gh", "pr", "create",
		"--title", opts.Task,
		"--body", body,
		"--label", "mochi-generated",
		"--head", opts.Branch,
	)
	cmd.Dir = opts.RepoRoot
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("gh pr create failed for %q: %w\n%s", opts.Slug, err, string(out))
	}

	// gh prints the PR URL as the last line of output
	return strings.TrimSpace(string(out)), nil
}

// buildPRBody constructs a markdown PR description from the task and agent log.
func buildPRBody(opts PROptions) string {
	var sb strings.Builder

	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("Implements task: **%s**\n\n", opts.Task))
	sb.WriteString("## Changes\n\n")
	sb.WriteString("_See commits for full change details._\n\n")

	if summary := readLogSummary(opts.LogPath); summary != "" {
		sb.WriteString("## Agent Log\n\n```\n")
		sb.WriteString(summary)
		sb.WriteString("\n```\n\n")
	}

	sb.WriteString("---\n")
	sb.WriteString("🤖 Generated by [MOCHI](https://github.com/thisguymartin/ai-forge)\n")

	return sb.String()
}

// readLogSummary returns the last 20 lines of the agent log file.
func readLogSummary(logPath string) string {
	f, err := os.Open(logPath)
	if err != nil {
		return ""
	}
	defer f.Close()

	var lines []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}

	if len(lines) > 20 {
		lines = lines[len(lines)-20:]
	}

	return strings.Join(lines, "\n")
}
